[tox]
isolated_build = True
envlist =
    py{39}-django{32}-drf{311,312,313,314}
    py{39}-django{40}-drf{313,314}
    py{39}-django{41}-drf{314}
    py{39}-django{42}-drf{314}

    py{310}-django{32}-drf{311,312,313,314}
    py{310}-django{40}-drf{313,314}
    py{310}-django{41}-drf{314}
    py{310}-django{42}-drf{314}
    py{310}-django{50}-drf{314}
    py{310}-django{51}-drf{314}

    py{311}-django{32}-drf{311,312,313,314}
    py{311}-django{40}-drf{313,314}
    py{311}-django{41}-drf{314}
    py{311}-django{42}-drf{315}
    py{311}-django{50}-drf{315}
    py{311}-django{51}-drf{315}

    py{312}-django{32}-drf{311,312,313,314}
    py{312}-django{40}-drf{313,314}
    py{312}-django{41}-drf{314}
    py{312}-django{42}-drf{315}
    py{312}-django{50}-drf{315}
    py{312}-django{51}-drf{315}

    py{313}-django{32}-drf{311,312,313,314}
    py{313}-django{40}-drf{313,314}
    py{313}-django{41}-drf{314}
    py{313}-django{42}-drf{315}
    py{313}-django{50}-drf{315}
    py{313}-django{51}-drf{315}

[gh-actions]
# Mapping of Python versions (MAJOR.MINOR) to Tox factors.
# When running Tox inside GitHub Actions, the `tox-gh-actions` plugin automatically:
# 1. Identifies the Python version used to run Tox.
# 2. Determines the corresponding Tox factor for that Python version, based on the `python` mapping below.
# 3. Narrows down the Tox `envlist` to environments that match the factor.
# For more details, please see the `tox-gh-actions` README [0] and architecture documentation [1].
# [0] https://github.com/ymyzk/tox-gh-actions/tree/v2.8.1
# [1] https://github.com/ymyzk/tox-gh-actions/blob/v2.8.1/ARCHITECTURE.md
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
deps =
    django-debug-toolbar>=1.0.0
    pytest>=2.7
    pytest-django>=3.4
    pytest-mock>=1.10
    drf38: djangorestframework~=3.8
    drf39: djangorestframework~=3.9
    drf310: djangorestframework~=3.10
    drf311: djangorestframework~=3.11
    drf312: djangorestframework~=3.12
    drf313: djangorestframework~=3.13
    drf314: djangorestframework~=3.14
    drf315: djangorestframework~=3.15
    django32: Django~=3.2
    django40: Django~=4.0
    django41: Django~=4.1
    django42: Django~=4.2
    django50: Django~=5.0
    django51: Django~=5.1
    redis>=3.0
    django-redis>=4.0
    ruff

commands =
    pytest {posargs}
    ruff check . --fix
