name: "Linting"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3

  - name: Set up Python 3.11
    uses: actions/setup-python@v4
    with:
      python-version: "3.11"

  - name: pre-commit
    uses: pre-commit/action@v3.0.0
